name: Format and Linter Checks

on:
  workflow_dispatch:
  workflow_call:

jobs:
  checks:
    if: github.repository_owner == 'viam-modules'
    runs-on: ubuntu-latest
    container: ghcr.io/viam-modules/universal-robots:amd64
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Format Check
        run: make format-check
      - name: Generate Config Database
        run: make generate-config-db
      - name: Run clang-check
        run: make run-clang-check
      - name: Run clang-tidy
        run: make run-clang-tidy
