name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    container: ghcr.io/viam-modules/universal-robots:${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: amd64
          runner: ubuntu-latest
        - arch: arm64
          runner: buildjet-4vcpu-ubuntu-2204-arm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: build
        run: make build
      - name: test
        run: make test
